# Generated by Django 3.0.7 on 2020-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=50)),
                ('Last_name', models.CharField(default='', max_length=50)),
                ('Services', models.CharField(default='', max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Message', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=50)),
                ('Email_address', models.EmailField(max_length=120)),
                ('Disease_Symptoms', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserprofileInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(default='', max_length=10)),
                ('First_name', models.CharField(default='', max_length=50)),
                ('Last_name', models.CharField(default='', max_length=50)),
                ('Email_address', models.EmailField(max_length=120)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
