# Generated by Django 3.0.2 on 2020-08-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointment_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
