# Generated by Django 3.0.2 on 2020-08-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_info',
            fields=[
                ('Doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Img', models.ImageField(upload_to='images/')),
                ('FullName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('Phone', models.CharField(max_length=10)),
                ('DateofBirth', models.DateField()),
                ('Experience', models.IntegerField(default='')),
                ('address_of_Hospital', models.CharField(default='', max_length=200)),
                ('Specialist', models.CharField(default='', max_length=50)),
                ('Qualifications', models.CharField(default='', max_length=50)),
                ('Date_of_joining', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
