# Generated by Django 3.0.2 on 2020-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_doctor_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_info',
            name='Img',
            field=models.CharField(default='', max_length=50),
        ),
    ]
